name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: heliumsystems/builder-erlang:1

    steps:
    - uses: actions/checkout@v2

    - name: Fetch git tags
      run: git fetch --prune --unshallow --tags

    - name: Build
      env:
        SANITIZE_ERLANG_NIFS: 1
      run: rebar3 compile

    - name: Run Dialyzer
      run: rebar3 dialyzer

    - name: Run tests
      env:
        # We turn off leak detection to reduce noise from leaking
        # processes that rebar exec()s before it actually runs the
        # tests.
        ASAN_OPTIONS: detect_leaks=0
      run: LD_PRELOAD="$(cc --print-file libasan.so)" rebar3 ct

    - name: Generate coverage report
      run: rebar3 covertool generate

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/h3.covertool.xml
        fail_ci_if_error: true
